[package]
name = "bmod-install"
description = "Plugin installer for bakkesmod"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
env_logger = "0.10"
error-iter = "0.4"
log = "0.4"
onlyargs = "0.1"
onlyargs_derive = "0.1"
onlyerror = "0.1"
ws-tool = "0.7"
