[package]
name = "test-plugin"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bmod = { path = "../.." }
cxx = "1"
# cpp = "0.5"

[build-dependencies]
bmod = { path = "../.." }
bmod-build = { path = "../../bmod-build" }
# cpp_build = "0.5"
